// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resEntity.proto

package com.iscas.sso.mix.ticket.share.agent.model;

public final class ResponseEntity {
  private ResponseEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iscas.sso.mix.ticket.share.agent.model.ResEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string desc = 3;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>string value = 4;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 4;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>string requestURL = 5;</code>
     */
    java.lang.String getRequestURL();
    /**
     * <code>string requestURL = 5;</code>
     */
    com.google.protobuf.ByteString
        getRequestURLBytes();

    /**
     * <code>uint64 tookInMillis = 6;</code>
     */
    long getTookInMillis();
  }
  /**
   * Protobuf type {@code com.iscas.sso.mix.ticket.share.agent.model.ResEntity}
   */
  public  static final class ResEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.iscas.sso.mix.ticket.share.agent.model.ResEntity)
      ResEntityOrBuilder {
    // Use ResEntity.newBuilder() to construct.
    private ResEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResEntity() {
      status_ = 0;
      message_ = "";
      desc_ = "";
      value_ = "";
      requestURL_ = "";
      tookInMillis_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              requestURL_ = s;
              break;
            }
            case 48: {

              tookInMillis_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity.class, com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>uint32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 3;
    private volatile java.lang.Object desc_;
    /**
     * <code>string desc = 3;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 4;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 4;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTURL_FIELD_NUMBER = 5;
    private volatile java.lang.Object requestURL_;
    /**
     * <code>string requestURL = 5;</code>
     */
    public java.lang.String getRequestURL() {
      java.lang.Object ref = requestURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestURL_ = s;
        return s;
      }
    }
    /**
     * <code>string requestURL = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRequestURLBytes() {
      java.lang.Object ref = requestURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOOKINMILLIS_FIELD_NUMBER = 6;
    private long tookInMillis_;
    /**
     * <code>uint64 tookInMillis = 6;</code>
     */
    public long getTookInMillis() {
      return tookInMillis_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeUInt32(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, desc_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, value_);
      }
      if (!getRequestURLBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, requestURL_);
      }
      if (tookInMillis_ != 0L) {
        output.writeUInt64(6, tookInMillis_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, desc_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, value_);
      }
      if (!getRequestURLBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, requestURL_);
      }
      if (tookInMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, tookInMillis_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity)) {
        return super.equals(obj);
      }
      com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity other = (com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity) obj;

      boolean result = true;
      result = result && (getStatus()
          == other.getStatus());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && getValue()
          .equals(other.getValue());
      result = result && getRequestURL()
          .equals(other.getRequestURL());
      result = result && (getTookInMillis()
          == other.getTookInMillis());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + REQUESTURL_FIELD_NUMBER;
      hash = (53 * hash) + getRequestURL().hashCode();
      hash = (37 * hash) + TOOKINMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTookInMillis());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iscas.sso.mix.ticket.share.agent.model.ResEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iscas.sso.mix.ticket.share.agent.model.ResEntity)
        com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity.class, com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity.Builder.class);
      }

      // Construct using com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        desc_ = "";

        value_ = "";

        requestURL_ = "";

        tookInMillis_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_descriptor;
      }

      public com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity getDefaultInstanceForType() {
        return com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity.getDefaultInstance();
      }

      public com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity build() {
        com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity buildPartial() {
        com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity result = new com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity(this);
        result.status_ = status_;
        result.message_ = message_;
        result.desc_ = desc_;
        result.value_ = value_;
        result.requestURL_ = requestURL_;
        result.tookInMillis_ = tookInMillis_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity) {
          return mergeFrom((com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity other) {
        if (other == com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.getRequestURL().isEmpty()) {
          requestURL_ = other.requestURL_;
          onChanged();
        }
        if (other.getTookInMillis() != 0L) {
          setTookInMillis(other.getTookInMillis());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ ;
      /**
       * <code>uint32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>uint32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 3;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 3;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 3;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 3;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 4;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 4;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 4;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 4;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 4;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestURL_ = "";
      /**
       * <code>string requestURL = 5;</code>
       */
      public java.lang.String getRequestURL() {
        java.lang.Object ref = requestURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestURL = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRequestURLBytes() {
        java.lang.Object ref = requestURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestURL = 5;</code>
       */
      public Builder setRequestURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestURL = 5;</code>
       */
      public Builder clearRequestURL() {
        
        requestURL_ = getDefaultInstance().getRequestURL();
        onChanged();
        return this;
      }
      /**
       * <code>string requestURL = 5;</code>
       */
      public Builder setRequestURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestURL_ = value;
        onChanged();
        return this;
      }

      private long tookInMillis_ ;
      /**
       * <code>uint64 tookInMillis = 6;</code>
       */
      public long getTookInMillis() {
        return tookInMillis_;
      }
      /**
       * <code>uint64 tookInMillis = 6;</code>
       */
      public Builder setTookInMillis(long value) {
        
        tookInMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 tookInMillis = 6;</code>
       */
      public Builder clearTookInMillis() {
        
        tookInMillis_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.iscas.sso.mix.ticket.share.agent.model.ResEntity)
    }

    // @@protoc_insertion_point(class_scope:com.iscas.sso.mix.ticket.share.agent.model.ResEntity)
    private static final com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity();
    }

    public static com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResEntity>
        PARSER = new com.google.protobuf.AbstractParser<ResEntity>() {
      public ResEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResEntity> getParserForType() {
      return PARSER;
    }

    public com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.ResEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017resEntity.proto\022*com.iscas.sso.mix.tic" +
      "ket.share.agent.model\"s\n\tResEntity\022\016\n\006st" +
      "atus\030\001 \001(\r\022\017\n\007message\030\002 \001(\t\022\014\n\004desc\030\003 \001(" +
      "\t\022\r\n\005value\030\004 \001(\t\022\022\n\nrequestURL\030\005 \001(\t\022\024\n\014" +
      "tookInMillis\030\006 \001(\004B<\n*com.iscas.sso.mix." +
      "ticket.share.agent.modelB\016ResponseEntity" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_sso_mix_ticket_share_agent_model_ResEntity_descriptor,
        new java.lang.String[] { "Status", "Message", "Desc", "Value", "RequestURL", "TookInMillis", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
