// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticketEntity.proto

package com.iscas.sso.mix.ticket.share.agent.model;

public final class TicketEntity {
  private TicketEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TkEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.TkEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *ticket
     * </pre>
     *
     * <code>string ticket = 1;</code>
     */
    java.lang.String getTicket();
    /**
     * <pre>
     *ticket
     * </pre>
     *
     * <code>string ticket = 1;</code>
     */
    com.google.protobuf.ByteString
        getTicketBytes();

    /**
     * <pre>
     *域名
     * </pre>
     *
     * <code>string domain = 2;</code>
     */
    java.lang.String getDomain();
    /**
     * <pre>
     *域名
     * </pre>
     *
     * <code>string domain = 2;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <pre>
     *过期时间，单位分钟
     * </pre>
     *
     * <code>uint32 expire = 3;</code>
     */
    int getExpire();
  }
  /**
   * Protobuf type {@code model.TkEntity}
   */
  public  static final class TkEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.TkEntity)
      TkEntityOrBuilder {
    // Use TkEntity.newBuilder() to construct.
    private TkEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TkEntity() {
      ticket_ = "";
      domain_ = "";
      expire_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TkEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ticket_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            case 24: {

              expire_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.internal_static_model_TkEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.internal_static_model_TkEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity.class, com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity.Builder.class);
    }

    public static final int TICKET_FIELD_NUMBER = 1;
    private volatile java.lang.Object ticket_;
    /**
     * <pre>
     *ticket
     * </pre>
     *
     * <code>string ticket = 1;</code>
     */
    public java.lang.String getTicket() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticket_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ticket
     * </pre>
     *
     * <code>string ticket = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTicketBytes() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object domain_;
    /**
     * <pre>
     *域名
     * </pre>
     *
     * <code>string domain = 2;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *域名
     * </pre>
     *
     * <code>string domain = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRE_FIELD_NUMBER = 3;
    private int expire_;
    /**
     * <pre>
     *过期时间，单位分钟
     * </pre>
     *
     * <code>uint32 expire = 3;</code>
     */
    public int getExpire() {
      return expire_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTicketBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ticket_);
      }
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, domain_);
      }
      if (expire_ != 0) {
        output.writeUInt32(3, expire_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTicketBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ticket_);
      }
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, domain_);
      }
      if (expire_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, expire_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity)) {
        return super.equals(obj);
      }
      com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity other = (com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity) obj;

      boolean result = true;
      result = result && getTicket()
          .equals(other.getTicket());
      result = result && getDomain()
          .equals(other.getDomain());
      result = result && (getExpire()
          == other.getExpire());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TICKET_FIELD_NUMBER;
      hash = (53 * hash) + getTicket().hashCode();
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      hash = (37 * hash) + EXPIRE_FIELD_NUMBER;
      hash = (53 * hash) + getExpire();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.TkEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.TkEntity)
        com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.internal_static_model_TkEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.internal_static_model_TkEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity.class, com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity.Builder.class);
      }

      // Construct using com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ticket_ = "";

        domain_ = "";

        expire_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.internal_static_model_TkEntity_descriptor;
      }

      public com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity getDefaultInstanceForType() {
        return com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity.getDefaultInstance();
      }

      public com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity build() {
        com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity buildPartial() {
        com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity result = new com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity(this);
        result.ticket_ = ticket_;
        result.domain_ = domain_;
        result.expire_ = expire_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity) {
          return mergeFrom((com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity other) {
        if (other == com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity.getDefaultInstance()) return this;
        if (!other.getTicket().isEmpty()) {
          ticket_ = other.ticket_;
          onChanged();
        }
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        if (other.getExpire() != 0) {
          setExpire(other.getExpire());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ticket_ = "";
      /**
       * <pre>
       *ticket
       * </pre>
       *
       * <code>string ticket = 1;</code>
       */
      public java.lang.String getTicket() {
        java.lang.Object ref = ticket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ticket_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *ticket
       * </pre>
       *
       * <code>string ticket = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTicketBytes() {
        java.lang.Object ref = ticket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ticket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ticket
       * </pre>
       *
       * <code>string ticket = 1;</code>
       */
      public Builder setTicket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ticket_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ticket
       * </pre>
       *
       * <code>string ticket = 1;</code>
       */
      public Builder clearTicket() {
        
        ticket_ = getDefaultInstance().getTicket();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ticket
       * </pre>
       *
       * <code>string ticket = 1;</code>
       */
      public Builder setTicketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ticket_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <pre>
       *域名
       * </pre>
       *
       * <code>string domain = 2;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *域名
       * </pre>
       *
       * <code>string domain = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *域名
       * </pre>
       *
       * <code>string domain = 2;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *域名
       * </pre>
       *
       * <code>string domain = 2;</code>
       */
      public Builder clearDomain() {
        
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *域名
       * </pre>
       *
       * <code>string domain = 2;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domain_ = value;
        onChanged();
        return this;
      }

      private int expire_ ;
      /**
       * <pre>
       *过期时间，单位分钟
       * </pre>
       *
       * <code>uint32 expire = 3;</code>
       */
      public int getExpire() {
        return expire_;
      }
      /**
       * <pre>
       *过期时间，单位分钟
       * </pre>
       *
       * <code>uint32 expire = 3;</code>
       */
      public Builder setExpire(int value) {
        
        expire_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *过期时间，单位分钟
       * </pre>
       *
       * <code>uint32 expire = 3;</code>
       */
      public Builder clearExpire() {
        
        expire_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:model.TkEntity)
    }

    // @@protoc_insertion_point(class_scope:model.TkEntity)
    private static final com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity();
    }

    public static com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TkEntity>
        PARSER = new com.google.protobuf.AbstractParser<TkEntity>() {
      public TkEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TkEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TkEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TkEntity> getParserForType() {
      return PARSER;
    }

    public com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.TkEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_TkEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_TkEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ticketEntity.proto\022\005model\":\n\010TkEntity\022" +
      "\016\n\006ticket\030\001 \001(\t\022\016\n\006domain\030\002 \001(\t\022\016\n\006expir" +
      "e\030\003 \001(\rB:\n*com.iscas.sso.mix.ticket.shar" +
      "e.agent.modelB\014TicketEntityb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_TkEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_TkEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_TkEntity_descriptor,
        new java.lang.String[] { "Ticket", "Domain", "Expire", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
