spring:
  application:
    name: seata-server2
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    # 池配置
    hikari:
      maximum-pool-size: 2
      pool-name: yuan-dev
# mybatis配置
mybatis:
  type-aliases-package: com.iscas.samples.distributed.transaction.seata.server2.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启数据表字段自动下划线转驼峰
    map-underscore-to-camel-case: true
# 打印sql
logging:
  level:
    com.varyuan.awesome.dao: debug
server:
  port: 7002