// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket.proto

package com.iscas.sso.mix.ticket.share.agent.service;

public final class TicketService {
  private TicketService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ticket.proto\022\007service\032\017resEntity.proto" +
      "\032\022ticketEntity.proto2n\n\006Ticket\0222\n\013storeT" +
      "icket\022\017.model.TkEntity\032\020.model.ResEntity" +
      "\"\000\0220\n\tgetTicket\022\017.model.TkEntity\032\020.model" +
      ".ResEntity\"\000B=\n,com.iscas.sso.mix.ticket" +
      ".share.agent.serviceB\rTicketServiceb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.getDescriptor(),
          com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.getDescriptor(),
        }, assigner);
    com.iscas.sso.mix.ticket.share.agent.model.ResponseEntity.getDescriptor();
    com.iscas.sso.mix.ticket.share.agent.model.TicketEntity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
