// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.iscas.sso.mix.auth.service;

public final class AuthService {
  private AuthService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\007service\032\017resEntity.proto\032\n" +
      "user.proto2[\n\004Auth\022(\n\005login\022\013.model.User" +
      "\032\020.model.ResEntity\"\000\022)\n\006verify\022\013.model.U" +
      "ser\032\020.model.ResEntity\"\000B-\n\036com.iscas.sso" +
      ".mix.auth.serviceB\013AuthServiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iscas.sso.mix.auth.model.ResponseEntity.getDescriptor(),
          com.iscas.sso.mix.auth.model.UserEntity.getDescriptor(),
        }, assigner);
    com.iscas.sso.mix.auth.model.ResponseEntity.getDescriptor();
    com.iscas.sso.mix.auth.model.UserEntity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
