/*
 * This file is generated by jOOQ.
 */
package com.iscas.biz.jooq.test.code;


import com.iscas.biz.jooq.test.code.tables.JooqTestTable;


/**
 * Convenience access to all tables in test_jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test_jooq.jooq_test_table</code>.
     */
    public static final JooqTestTable JOOQ_TEST_TABLE = JooqTestTable.JOOQ_TEST_TABLE;
}
