/*
 * This file is generated by jOOQ.
 */
package com.iscas.biz.jooq.test.code.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTestTable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;

    public JooqTestTable() {}

    public JooqTestTable(JooqTestTable value) {
        this.id = value.id;
        this.name = value.name;
    }

    public JooqTestTable(
        Integer id,
        String  name
    ) {
        this.id = id;
        this.name = name;
    }

    /**
     * Getter for <code>test_jooq.jooq_test_table.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>test_jooq.jooq_test_table.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>test_jooq.jooq_test_table.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>test_jooq.jooq_test_table.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqTestTable (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
