/*
 * This file is generated by jOOQ.
 */
package com.iscas.biz.jooq.test.code.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sample implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  c1;
    private Long    c2;
    private Byte    c3;
    private Boolean c4;

    public Sample() {}

    public Sample(Sample value) {
        this.id = value.id;
        this.c1 = value.c1;
        this.c2 = value.c2;
        this.c3 = value.c3;
        this.c4 = value.c4;
    }

    public Sample(
        Integer id,
        String  c1,
        Long    c2,
        Byte    c3,
        Boolean c4
    ) {
        this.id = id;
        this.c1 = c1;
        this.c2 = c2;
        this.c3 = c3;
        this.c4 = c4;
    }

    /**
     * Getter for <code>test_jooq.sample.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>test_jooq.sample.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>test_jooq.sample.c1</code>.
     */
    public String getC1() {
        return this.c1;
    }

    /**
     * Setter for <code>test_jooq.sample.c1</code>.
     */
    public void setC1(String c1) {
        this.c1 = c1;
    }

    /**
     * Getter for <code>test_jooq.sample.c2</code>.
     */
    public Long getC2() {
        return this.c2;
    }

    /**
     * Setter for <code>test_jooq.sample.c2</code>.
     */
    public void setC2(Long c2) {
        this.c2 = c2;
    }

    /**
     * Getter for <code>test_jooq.sample.c3</code>.
     */
    public Byte getC3() {
        return this.c3;
    }

    /**
     * Setter for <code>test_jooq.sample.c3</code>.
     */
    public void setC3(Byte c3) {
        this.c3 = c3;
    }

    /**
     * Getter for <code>test_jooq.sample.c4</code>.
     */
    public Boolean getC4() {
        return this.c4;
    }

    /**
     * Setter for <code>test_jooq.sample.c4</code>.
     */
    public void setC4(Boolean c4) {
        this.c4 = c4;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sample (");

        sb.append(id);
        sb.append(", ").append(c1);
        sb.append(", ").append(c2);
        sb.append(", ").append(c3);
        sb.append(", ").append(c4);

        sb.append(")");
        return sb.toString();
    }
}
